package org.POJO;

// Generated 16-Jul-2014 02:41:33 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FieldMt generated by hbm2java
 */
@Entity
@Table(name = "field_mt", catalog = "itechcrm")
public class FieldMt implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7277597471114759132L;
	private Integer fieldid;
	private String fieldname;
	private Set<UserViewDetails> userViewDetailses = new HashSet<UserViewDetails>(
			0);

	public FieldMt() {
	}

	public FieldMt(String fieldname) {
		this.fieldname = fieldname;
	}

	public FieldMt(String fieldname, Set<UserViewDetails> userViewDetailses) {
		this.fieldname = fieldname;
		this.userViewDetailses = userViewDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "fieldid", unique = true, nullable = false)
	public Integer getFieldid() {
		return this.fieldid;
	}

	public void setFieldid(Integer fieldid) {
		this.fieldid = fieldid;
	}

	@Column(name = "fieldname", nullable = false)
	public String getFieldname() {
		return this.fieldname;
	}

	public void setFieldname(String fieldname) {
		this.fieldname = fieldname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fieldMt")
	public Set<UserViewDetails> getUserViewDetailses() {
		return this.userViewDetailses;
	}

	public void setUserViewDetailses(Set<UserViewDetails> userViewDetailses) {
		this.userViewDetailses = userViewDetailses;
	}

}
