package org.POJO;

// Generated 16-Jul-2014 02:41:33 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserViewDetails generated by hbm2java
 */
@Entity
@Table(name = "user_view_details", catalog = "itechcrm")
public class UserViewDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5953878136200382800L;
	private Integer labelid;
	private UserView userView;
	private FieldMt fieldMt;
	private String data;
	private String label;

	public UserViewDetails() {
	}

	public UserViewDetails(UserView userView, FieldMt fieldMt, String data,
			String label) {
		this.userView = userView;
		this.fieldMt = fieldMt;
		this.data = data;
		this.label = label;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "labelid", unique = true, nullable = false)
	public Integer getLabelid() {
		return this.labelid;
	}

	public void setLabelid(Integer labelid) {
		this.labelid = labelid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "viewid")
	public UserView getUserView() {
		return this.userView;
	}

	public void setUserView(UserView userView) {
		this.userView = userView;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fieldid")
	public FieldMt getFieldMt() {
		return this.fieldMt;
	}

	public void setFieldMt(FieldMt fieldMt) {
		this.fieldMt = fieldMt;
	}

	@Column(name = "data")
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Column(name = "label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

}
