package org.POJO;

// Generated 16-Jul-2014 02:41:33 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserAccounts generated by hbm2java
 */
@Entity
@Table(name = "user_accounts", catalog = "itechcrm")
public class UserAccounts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7769435335147857606L;
	private Integer userid;
	private String username;
	private String password;
	private Set<UserView> userViews = new HashSet<UserView>(0);

	public UserAccounts() {
	}

	public UserAccounts(String username, String password,
			Set<UserView> userViews) {
		this.username = username;
		this.password = password;
		this.userViews = userViews;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "userid", unique = true, nullable = false)
	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccounts")
	public Set<UserView> getUserViews() {
		return this.userViews;
	}

	public void setUserViews(Set<UserView> userViews) {
		this.userViews = userViews;
	}

}
